avoid NoOptionError if ignore not configured
If the `ignore` option is not configured, pylint_runner dies with:

    configparser.NoOptionError: No option 'ignore' in section: 'MASTER'

Avoid this by checking that the option is present using `#has_option()`
before `#get()`.  (Note: It is not necessary to check that the `MASTER`
section exists, since `#has_option()` returns `False` in that case.)

Signed-off-by: Kevin Locke <kevin@kevinlocke.name>